[[redirects]]
  from = "https://app-dev-doecom.netlify.app"
  to = "https://app-dev.doecom.org"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
